services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: iprwc
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"

networks:
  db:
    driver: bridge
volumes:
  db:

