services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: noah
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
      POSTGRES_DB: customer
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"

networks:
  db:
    driver: bridge
volumes:
  db:

